[package]
name = "render"
version = "0.1.0"
edition = "2021"

[dependencies]
displaydoc.workspace = true

mem = { path = "../mem" }
bvh = { path = "../bvh" }
geom = { path = "../geom" }
scene = { path = "../scene" }
